# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
    {
        :name => "k8s-master-1",
        :type => "master",
        :box => "hashicorp-vagrant/ubuntu-16.04",
        :box_version => "1.0.1",
        :eth1 => "172.28.128.4",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "k8s-master-2",
        :type => "master",
        :box => "hashicorp-vagrant/ubuntu-16.04",
        :box_version => "1.0.1",
        :eth1 => "172.28.128.5",
        :mem => "2048",
        :cpu => "2"
    }
]

Vagrant.configure("2") do |config|
    nodes.each do |node|
        config.vm.define node[:name] do |config|
            config.vm.box = node[:box]
            config.vm.box_version = node[:box_version]
            config.vm.hostname = node[:name]
            config.vm.network :private_network, ip: node[:eth1]
            #config.vm.network "private_network", type: "dhcp"

            config.vm.provider "virtualbox" do |v|
                v.name = node[:name]
            	v.customize ["modifyvm", :id, "--groups", "/Custom Development"]
                v.customize ["modifyvm", :id, "--memory", node[:mem]]
                v.customize ["modifyvm", :id, "--cpus", node[:cpu]]
            end

            #we cannot use this because we can't install the docker version we want - https://github.com/hashicorp/vagrant/issues/4871
            #config.vm.provision "docker"
            #config.vm.provision "file", source: "calicoctl.cfg", destination: "/home/vagrant/calicoctl.cfg"
            #config.vm.provision "file", source: "calico-ip-pool.yaml", destination: "/home/vagrant/calico-ip-pool.yaml"

            config.vm.provision "shell", path: "PackageInstallation.sh"

            if node[:type] == "master"
                config.vm.provision "shell", path: "ConfigureMaster.sh"
            else
                config.vm.provision "shell", path: "ConfigureNode.sh"
            end
        end
    end
end 